-- ============================================================
-- 01_tables.sql — выполняется автоматически при ПЕРВОМ старте
-- контейнера PostgreSQL (docker-entrypoint-initdb.d).
-- Создаёт схему данных, соответствующую модели EF Core.
-- ============================================================

CREATE TABLE IF NOT EXISTS "Books" (
    "Id"     integer GENERATED BY DEFAULT AS IDENTITY,
    "Title"  text NOT NULL,
    "Author" text NOT NULL,
    "Genre"  text NOT NULL,
    "Year"   integer NOT NULL DEFAULT 0,
    "Pages"  integer NOT NULL,
    "Toc"    xml NULL,
    CONSTRAINT "PK_Books" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "BookFiles" (
    "Id"       integer GENERATED BY DEFAULT AS IDENTITY,
    "BookId"   integer NOT NULL,
    "Format"   text NOT NULL,
    "FilePath" text NOT NULL,
    "FileName" text NOT NULL,
    CONSTRAINT "PK_BookFiles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BookFiles_Books_BookId" FOREIGN KEY ("BookId")
        REFERENCES "Books" ("Id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_BookFiles_BookId" ON "BookFiles" ("BookId");

CREATE TABLE IF NOT EXISTS "UserBookProgress" (
    "Id"           integer GENERATED BY DEFAULT AS IDENTITY,
    "BookId"       integer NOT NULL,
    "LastReadPage" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_UserBookProgress" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserBookProgress_Books_BookId" FOREIGN KEY ("BookId")
        REFERENCES "Books" ("Id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_UserBookProgress_BookId" ON "UserBookProgress" ("BookId");

CREATE TABLE IF NOT EXISTS "Rating" (
    "Id"         integer GENERATED BY DEFAULT AS IDENTITY,
    "BookId"     integer NOT NULL,
    "BookRating" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Rating" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Rating_Books_BookId" FOREIGN KEY ("BookId")
        REFERENCES "Books" ("Id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Rating_BookId" ON "Rating" ("BookId");
