<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlackBook.Data\BlackBook.Data.csproj" />
    <ProjectReference Include="..\BookStorageService\BookStorageService.csproj" />
    <ProjectReference Include="..\Mega.Client\Mega.Client.csproj" />
  </ItemGroup>

</Project>
